// ====================================
//             Requirements
// ====================================
const mongoose = require("mongoose");
const Schema = mongoose.Schema;

// ====================================
//            Schema & Model
// ====================================
const bookingSchema = new Schema({
	// an id for the booking will be automatically generated by mongo and named _id
	user: { type: Schema.Types.ObjectId, ref: "User", required: true },
	hospital: { type: Schema.Types.ObjectId, ref: "Hospital", required: true },
	ambulance: { type: Schema.Types.ObjectId, ref: "Ambulance", required: true },
	driver: { type: Schema.Types.ObjectId, ref: "Driver", required: true },
	timeMoved: { type: Date },
	timeArrived: { type: Date },
	state: { type: String, enum: ["current", "previous"], required: true },
	clientLocation: { longitude: String, latitude: String },
	issueDetails: { type: String },
});

// model
const booking = mongoose.model("Booking", bookingSchema);

// ====================================
//             Export
// ====================================
module.exports = { booking };
